### ISSUE TITLE
[ENHANCEMENT] Delete `positions(::Type, pos::Tuple)`, use `position.(::Type, pos::Tuple)` instead

### ISSUE THREAD

**Issue by mtfishman** [ITensor/TypeParameterAccessors.jl#14]

**Comment by lkdvos** [comment]
I think this was a type stability thing, `ntuple` seems better on the compiler. (As always, I would have to double check this now, these things are heavily interdependent and moving/removing one thing has non-trivial implications in other places). Keep in mind that `positions` is an unexported function, so this is mainly for internal usage. If you want, we could also consider changing that to `_positions` to be more concrete on that?

**Comment by mtfishman** [comment]
That makes sense, some of these were just writing things that came to mind as I was looking over the latest PR.
